export const SEARCH_TEXT_CHANGE = 'SEARCH_TEXT_CHANGE';
export const SEARCH_RESULTS_RECEIVED = 'SEARCH_RESULTS_RECEIVED';
export const SEARCH_CLEAR_RESULTS = 'SEARCH_CLEAR_RESULTS';
export const VOUCHER_DETAILS_RECEIVED = 'VOUCHER_DETAILS_RECEIVED';
export const USER_ACCESSTOKEN_RECEIVED = 'USER_ACCESSTOKEN_RECEIVED';
export const USER_INFO_RECEIVED = 'USER_INFO_RECEIVED';